#version: '3'

# services:
#   myapp:
#     build: .
#     container_name: myapp
#     restart: always
#     ports:
#       - 8080:80
#     volumes: 
#       - ./html:/usr/share/nginx/html
      
#   mysqli:
#     image: mysql:8
#     container_name: mysql
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASES: mybanc
#     ports:
#       - 3306:3306
#     volumes:
#       - .mysql:/var/lib/mysql

#   rabbitmq:
#     image: rabbitmq:3-management
#     container_name: rabbitmq
#     restart: always
#     environment:
#       RABBITMQ_DEFAULT_USER: rooting
#       RABBITMQ_DEFAULT_PASS: rooting
#     ports:
#       - 5672:5672
#       - 15672:15672

version: '3'

services:
  web:
    image: nginx:1.13
    ports:
      - "8080:80"
    volumes:
      - ./projeto:/src
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks: 
      - production-network
    depends_on:
      - php

  php:
    image: php:7.1-fpm
    volumes:
      - ./projeto:/src
    ports:
      - "9000:9000"
    networks: 
      - production-network
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7.20
    networks: 
      - production-network
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123.456

networks: 
  production-network: 
    driver: bridge
