on: [push, pull_request]
name: Test
jobs:
    roave_bc_check:
        name: Roave BC Check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: roave-bc-check-phpstan
              uses: Nyholm/roave-bc-check-docker@0.1.0
            
