on: [push, pull_request]
name: components security
jobs:
    roave_bc_check:
        name: components security
        runs-on: ubuntu-latest
        steps:
              - name: pipeline-components-php-security-checker
                uses: pipeline-components/php-security-checker@v0.10.4
                with:
                    lockFile: './projeto'
            
            
