name: Generate PHP class

on:
  push:

jobs:
  get_php_classes_list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkouting project code...
        uses: actions/checkout@v2
        
      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.1
          extensions: curl, gd, pdo_mysql, json, mbstring, pcre, session
          ini-values: post_max_size=256M
          coverage: none
          tools: composer:v2
          
      - name: Install Composer dependencies (with dev)
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
        
      - name: Generate PHP project classes list file
        uses: impresscms-dev/generate-php-project-classes-list-file-action@v1.0.0
        with:
          output_file: ./projeto/php-classes.lst
          
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ./php-classes.lst

# Ação do GitHub para gerar um arquivo com a lista de classes do projeto PHP
